CREATE DATABASE IF NOT EXISTS preguntas_respuestas;

USE preguntas_respuestas;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo ENUM('Masculino', 'Femenino', 'Prefiero no cargarlo') DEFAULT 'Prefiero no cargarlo',
    pais VARCHAR(100),
    ciudad VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    nombre_usuario VARCHAR(50) UNIQUE NOT NULL,
    foto_perfil VARCHAR(255) DEFAULT NULL,
    rol ENUM('Jugador', 'Administrador', 'Editor') DEFAULT 'Jugador',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_registro ENUM('Activo', 'Inactivo') DEFAULT 'Inactivo',
    token_verificacion INT DEFAULT NULL
);

INSERT INTO
    usuarios (
        nombre,
        fecha_nacimiento,
        sexo,
        pais,
        ciudad,
        email,
        password,
        nombre_usuario,
        rol,
        estado_registro,
        token_verificacion,
        foto_perfil
    )
VALUES
    (
        'Administrador General',
        '1990-10-10',
        'Prefiero no cargarlo',
        'Argentina',
        'Buenos Aires',
        'admin@admin.com',
        '$2y$10$ZI6Bft2VF/7ibKP5Hc1n.OMpBpwsO6J7sVC3tsN0UFUoYdPqL0ZqK',
        'admin',
        'Administrador',
        'Activo',
        NULL,
        NULL
    ); 

CREATE TABLE categorias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    color VARCHAR(7) DEFAULT '#FFFFFF',
    icono VARCHAR(50) DEFAULT '❓',
    descripcion TEXT,
    activa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categorias (nombre, color, icono, descripcion) VALUES 
('Deporte', '#FF6B35', '⚽', 'Preguntas sobre deportes, atletas y competiciones'),
('Entretenimiento', '#F7931E', '🎬', 'Cine, música, televisión y espectáculos'),
('Historia', '#8B4513', '📚', 'Eventos históricos, personajes y civilizaciones'),
('Ciencia', '#4CAF50', '🔬', 'Física, química, biología y tecnología'),
('Arte', '#9C27B0', '🎨', 'Pintura, escultura, literatura y bellas artes'),
('Geografía', '#2196F3', '🌍', 'Países, capitales, ríos, montañas y mapas');

CREATE TABLE preguntas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    categoria_id INT NOT NULL,
    pregunta TEXT NOT NULL,
    respuesta_1 TEXT NOT NULL,
    respuesta_2 TEXT NOT NULL,
    respuesta_3 TEXT NOT NULL,
    respuesta_4 TEXT NOT NULL,
    respuesta_correcta TINYINT NOT NULL CHECK (respuesta_correcta BETWEEN 1 AND 4),
    veces_entregada INT DEFAULT 0,
    veces_incorrecta INT DEFAULT 0,
    porcentaje_acierto DECIMAL(5,2) DEFAULT 0.00,
    nivel_dificultad ENUM('Fácil', 'Medio', 'Difícil') DEFAULT 'Medio',
    activa BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE CASCADE,
    INDEX idx_categoria (categoria_id),
    INDEX idx_dificultad (nivel_dificultad),
    INDEX idx_activa (activa)
);


DELETE FROM preguntas;
INSERT INTO preguntas (categoria_id, pregunta, respuesta_1, respuesta_2, respuesta_3, respuesta_4, respuesta_correcta) VALUES
(1, '¿En qué año se celebró el primer Mundial de Fútbol?', '1928', '1930', '1932', '1934', 2),
(1, '¿Cuál es el único país que ha participado en todos los Mundiales de Fútbol?', 'Brasil', 'Argentina', 'Alemania', 'Italia', 1),
(1, '¿Quién es el máximo goleador histórico de los Mundiales?', 'Pelé', 'Diego Maradona', 'Miroslav Klose', 'Ronaldo', 3),
(1, '¿En qué estadio se jugó la final del Mundial 2014?', 'Estadio Nacional', 'Maracaná', 'Arena Corinthians', 'Mané Garrincha', 2),
(1, '¿Cuántos jugadores conforman un equipo de fútbol en el campo?', '10', '11', '12', '9', 2),
(1, '¿Qué selección ganó la Eurocopa 2016?', 'Francia', 'Portugal', 'Alemania', 'España', 2),
(1, '¿Cuál es el club con más Champions League ganadas?', 'Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Munich', 3),
(1, '¿En qué año Diego Maradona anotó el "Gol del Siglo"?', '1984', '1986', '1988', '1990', 2),
(1, '¿Cuál es el estadio más grande del mundo?', 'Camp Nou', 'Wembley', 'Estadio Azteca', 'Rungrado', 4),
(1, '¿Qué país organizó el Mundial de Fútbol 2018?', 'Brasil', 'Rusia', 'Qatar', 'Sudáfrica', 2),
(1, '¿Cuánto dura un partido de fútbol oficial?', '80 minutos', '90 minutos', '100 minutos', '120 minutos', 2),
(1, '¿Qué jugador tiene más Balones de Oro?', 'Cristiano Ronaldo', 'Lionel Messi', 'Michel Platini', 'Johan Cruyff', 2),
(1, '¿En qué posición jugaba Roberto Carlos?', 'Portero', 'Defensa', 'Mediocampista', 'Delantero', 2),
(1, '¿Cuál es la Copa continental de fútbol más antigua?', 'Copa América', 'Eurocopa', 'Copa Africana', 'Copa Asiática', 1),
(1, '¿Qué significa "offside" en fútbol?', 'Fuera de juego', 'Tiro libre', 'Tarjeta amarilla', 'Corner', 1),
(1, '¿En qué Mundial debutó la tecnología del VAR?', 'Brasil 2014', 'Rusia 2018', 'Qatar 2022', 'Sudáfrica 2010', 2),
(1, '¿Cuál es el récord de goles en un Mundial individual?', '11 goles', '13 goles', '15 goles', '16 goles', 2),
(1, '¿Qué selección es conocida como "La Roja"?', 'España', 'Suiza', 'Portugal', 'Polonia', 1),
(1, '¿En qué año se fundó la FIFA?', '1902', '1904', '1906', '1908', 2),
(1, '¿Cuál es el club más antiguo del mundo aún en funcionamiento?', 'Sheffield FC', 'Notts County', 'Stoke City', 'Wrexham', 1),
(1, '¿Cuántos jugadores tiene un equipo de básquet en cancha?', '4', '5', '6', '7', 2),
(1, '¿Cuánto mide la cancha de básquet profesional?', '28x15 metros', '30x16 metros', '26x14 metros', '32x18 metros', 1),
(1, '¿Quién inventó el básquet?', 'James Naismith', 'William Morgan', 'Walter Camp', 'Abner Doubleday', 1),
(1, '¿Cuántos puntos vale un tiro libre?', '1 punto', '2 puntos', '3 puntos', '4 puntos', 1),
(1, '¿A qué altura está el aro de básquet?', '3.00 metros', '3.05 metros', '3.10 metros', '3.15 metros', 2),
(1, '¿Cuál es el récord de puntos en un partido NBA?', '81 puntos', '100 puntos', '120 puntos', '150 puntos', 2),
(1, '¿Qué jugador tiene más anillos NBA?', 'Michael Jordan', 'Bill Russell', 'Kobe Bryant', 'LeBron James', 2),
(1, '¿En qué año se creó la NBA?', '1946', '1949', '1950', '1953', 1),
(1, '¿Cuántos equipos participan actualmente en la NBA?', '28', '30', '32', '34', 2),
(1, '¿Qué significa "triple-doble" en básquet?', 'Tres triples', 'Doble dígito en 3 estadísticas', 'Tres faltas', 'Doble tiempo', 2),
(1, '¿Cuál es el equipo con más títulos NBA?', 'Lakers', 'Celtics', 'Bulls', 'Warriors', 2),
(1, '¿Cuánto dura un cuarto en la NBA?', '10 minutos', '12 minutos', '15 minutos', '20 minutos', 2),
(1, '¿Qué jugador es conocido como "His Airness"?', 'Magic Johnson', 'Larry Bird', 'Michael Jordan', 'Shaquille O Neal', 3),
(1, '¿En qué ciudad están los Lakers actualmente?', 'Minneapolis', 'Los Ángeles', 'Oakland', 'Sacramento', 2),
(1, '¿Cuál es la línea de tres puntos en la NBA?', '6.75 metros', '7.24 metros', '7.50 metros', '8.00 metros', 2),
(1, '¿Cuántos Grand Slams hay en el tenis?', '3', '4', '5', '6', 2),
(1, '¿Cuál es el torneo más antiguo de tenis?', 'US Open', 'Roland Garros', 'Wimbledon', 'Australian Open', 3),
(1, '¿En qué superficie se juega Roland Garros?', 'Césped', 'Polvo de ladrillo', 'Cemento', 'Sintético', 2),
(1, '¿Cuántos sets debe ganar un hombre para ganar un Grand Slam?', '2 de 3', '3 de 5', '4 de 7', '5 de 9', 2),
(1, '¿Qué significa "deuce" en tenis?', '40-40', '30-30', 'Empate', 'Ventaja', 1),
(1, '¿Quién tiene más Grand Slams masculinos?', 'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Pete Sampras', 3),
(1, '¿En qué mes se juega Wimbledon?', 'Mayo', 'Junio', 'Julio', 'Agosto', 3),
(1, '¿Cuál es la velocidad récord de un saque?', '246 km/h', '253 km/h', '263 km/h', '273 km/h', 3),
(1, '¿Qué jugadora tiene más Grand Slams?', 'Serena Williams', 'Steffi Graf', 'Margaret Court', 'Martina Navratilova', 3),
(1, '¿Cuándo se introdujo el tie-break?', '1965', '1970', '1975', '1980', 2),
(1, '¿Qué altura tiene la red de tenis?', '0.91 metros', '0.95 metros', '1.00 metros', '1.05 metros', 1),
(1, '¿En qué país se originó el tenis moderno?', 'Francia', 'Inglaterra', 'Estados Unidos', 'Australia', 2),
(1, '¿Qué significa un "ace" en tenis?', 'Punto ganador', 'Saque directo', 'Doble falta', 'Match point', 2),
(1, '¿Cuál es la Copa del mundo por equipos masculina?', 'Copa Davis', 'Copa Masters', 'Copa ATP', 'Copa Grand Slam', 1),
(1, '¿Quién ganó más veces Roland Garros?', 'Björn Borg', 'Rafael Nadal', 'Ivan Lendl', 'Gustavo Kuerten', 2),
(1, '¿En qué año se celebraron los primeros Juegos Olímpicos modernos?', '1894', '1896', '1900', '1904', 2),
(1, '¿Dónde se celebraron los primeros Juegos Olímpicos modernos?', 'París', 'Londres', 'Atenas', 'Roma', 3),
(1, '¿Cada cuántos años se celebran los Juegos Olímpicos?', '3 años', '4 años', '5 años', '6 años', 2),
(1, '¿Quién tiene más medallas olímpicas en la historia?', 'Carl Lewis', 'Mark Spitz', 'Michael Phelps', 'Larisa Latynina', 3),
(1, '¿Cuál es el récord mundial de los 100 metros planos?', '9.58 segundos', '9.63 segundos', '9.69 segundos', '9.74 segundos', 1),
(1, '¿Quién tiene el récord de los 100 metros?', 'Carl Lewis', 'Usain Bolt', 'Justin Gatlin', 'Tyson Gay', 2),
(1, '¿En qué disciplina compitió Jesse Owens?', 'Natación', 'Atletismo', 'Gimnasia', 'Boxeo', 2),
(1, '¿Cuántas disciplinas tiene el decatlón?', '8', '10', '12', '15', 2),
(1, '¿Qué distancia tiene la maratón olímpica?', '40 km', '42.195 km', '45 km', '50 km', 2),
(1, '¿En qué ciudad se realizaron los Juegos Olímpicos de 2016?', 'Londres', 'Tokio', 'Río de Janeiro', 'Pekín', 3),
(1, '¿Cuál es el lema olímpico?', 'Más rápido, más alto, más fuerte', 'Citius, Altius, Fortius', 'Ambas son correctas', 'Ninguna es correcta', 3),
(1, '¿Qué representa cada aro olímpico?', 'Los 5 elementos', 'Los 5 continentes', 'Los 5 deportes', 'Los 5 valores', 2),
(1, '¿En qué año se incluyeron las mujeres en los Juegos Olímpicos?', '1896', '1900', '1912', '1924', 2),
(1, '¿Cuál es el récord mundial de salto de altura?', '2.40 metros', '2.45 metros', '2.50 metros', '2.55 metros', 2),
(1, '¿Quién encendió la antorcha olímpica en Atlanta 1996?', 'Carl Lewis', 'Muhammad Ali', 'Michael Johnson', 'Edwin Moses', 2),
(1, '¿Cuántas medallas de oro ganó Michael Phelps?', '18', '21', '23', '25', 3),
(1, '¿En qué disciplina compite Eliud Kipchoge?', 'Velocidad', 'Maratón', 'Salto', 'Lanzamiento', 2),
(1, '¿Cuál fue el primer país en organizar Juegos Olímpicos de Invierno?', 'Suiza', 'Francia', 'Noruega', 'Austria', 2),
(1, '¿En qué año se separaron los Juegos de Verano e Invierno?', '1992', '1994', '1996', '1998', 2),
(1, '¿Qué atleta fue conocido como "El Rayo"?', 'Carl Lewis', 'Usain Bolt', 'Jesse Owens', 'Ben Johnson', 2),
(1, '¿En qué deporte se usa el término "slam dunk"?', 'Voleibol', 'Tenis', 'Básquet', 'Fútbol Americano', 3),
(1, '¿Cuántos jugadores tiene un equipo de rugby?', '13', '15', '17', '19', 2),
(1, '¿En qué deporte se compite por la Copa Davis?', 'Golf', 'Tenis', 'Críquet', 'Polo', 2),
(1, '¿Cuántas bases tiene un campo de béisbol?', '3', '4', '5', '6', 2),
(1, '¿En qué deporte se usa un "driver"?', 'Tenis', 'Golf', 'Críquet', 'Hockey', 2),
(1, '¿Cuántos jugadores forman un equipo de vóley?', '5', '6', '7', '8', 2),
(1, '¿En qué deporte se compite por el Masters de Augusta?', 'Tenis', 'Golf', 'Hípica', 'Automovilismo', 2),
(1, '¿Cuántos rounds tiene una pelea profesional de boxeo?', '10', '12', '15', '20', 2),
(1, '¿En qué deporte se usa una "paleta"?', 'Ping pong', 'Pádel', 'Squash', 'Todos los anteriores', 4),
(1, '¿Cuál es el torneo de golf más prestigioso?', 'Masters', 'US Open', 'British Open', 'PGA Championship', 1),
(1, '¿En qué deporte se compite en el Tour de Francia?', 'Automovilismo', 'Motociclismo', 'Ciclismo', 'Atletismo', 3),
(1, '¿Cuántos puntos vale un try en rugby?', '3 puntos', '4 puntos', '5 puntos', '6 puntos', 3),
(1, '¿En qué deporte se usa el término "strike"?', 'Bowling', 'Béisbol', 'Ambos', 'Ninguno', 3),
(1, '¿Cuántas categorías de peso hay en boxeo profesional?', '8', '12', '17', '21', 3),
(1, '¿En qué deporte se compite por la Copa Ryder?', 'Tenis', 'Golf', 'Polo', 'Críquet', 2),
(1, '¿Cuánto dura un partido de hockey sobre hielo?', '60 minutos', '90 minutos', '120 minutos', '180 minutos', 1),
(1, '¿En qué deporte se usa un "birdie"?', 'Bádminton', 'Golf', 'Ambos', 'Ninguno', 3),
(1, '¿Cuántos jugadores forman un equipo de waterpolo?', '6', '7', '8', '9', 2),
(1, '¿En qué deporte se compite por la Copa Stanley?', 'Hockey', 'Fútbol', 'Básquet', 'Béisbol', 1),
(1, '¿Cuál es el récord mundial de natación en 100m libre?', '46.91', '47.05', '47.32', '47.58', 1),
(1, '¿En qué deporte se usa una "raqueta"?', 'Tenis', 'Bádminton', 'Squash', 'Todos los anteriores', 4),
(1, '¿Cuántas pistas tiene una piscina olímpica?', '6', '8', '10', '12', 2),
(1, '¿En qué deporte se compite por el Giro de Italia?', 'Automovilismo', 'Motociclismo', 'Ciclismo', 'Maratón', 3),
(1, '¿Cuántos sets se juegan en vóley masculino?', '3 de 5', '2 de 3', 'Al mejor de 7', 'Tiempo corrido', 1),
(1, '¿En qué deporte se usa el término "knock out"?', 'Boxeo', 'Fútbol', 'Básquet', 'Tenis', 1),
(1, '¿Cuál es la prueba más larga en natación olímpica?', '800m', '1500m', '3000m', '5000m', 2),
(1, '¿En qué deporte se compite por la Copa América (vela)?', 'Regata', 'Surf', 'Remo', 'Windsurf', 1),
(1, '¿Cuántos jugadores tiene un equipo de balonmano?', '6', '7', '8', '9', 2),
(1, '¿En qué deporte se usa el término "spare"?', 'Bowling', 'Golf', 'Billar', 'Dardos', 1),
(1, '¿Cuál es la distancia de un triatlón Ironman?', '3.8km-180km-42km', '1.5km-40km-10km', '2km-90km-21km', '5km-200km-50km', 1);

INSERT INTO preguntas (categoria_id, pregunta, respuesta_1, respuesta_2, respuesta_3, respuesta_4, respuesta_correcta) VALUES
(2, '¿Quién dirigió la película "Pulp Fiction"?', 'Steven Spielberg', 'Quentin Tarantino', 'Martin Scorsese', 'Christopher Nolan', 2),
(2, '¿Cuál es la película más taquillera de la historia?', 'Titanic', 'Avatar', 'Avengers: Endgame', 'Star Wars', 3),
(2, '¿En qué año se estrenó "El Padrino"?', '1970', '1972', '1974', '1976', 2),
(2, '¿Quién interpretó a Jack Sparrow?', 'Orlando Bloom', 'Johnny Depp', 'Will Smith', 'Brad Pitt', 2),
(2, '¿Cuál fue la primera película de Pixar?', 'Bichos', 'Toy Story', 'Monsters Inc', 'Buscando a Nemo', 2),
(2, '¿Quién dirigió "E.T."?', 'George Lucas', 'Steven Spielberg', 'James Cameron', 'Ridley Scott', 2),
(2, '¿En qué película aparece la frase "Que la fuerza te acompañe"?', 'Star Trek', 'Star Wars', 'Guardianes de la Galaxia', 'Blade Runner', 2),
(2, '¿Cuál es la película más premiada en los Oscar?', 'Titanic', 'Ben-Hur', 'El Señor de los Anillos', 'Todas empatadas', 4),
(2, '¿Quién interpretó a Forrest Gump?', 'Tom Cruise', 'Tom Hanks', 'Will Smith', 'Kevin Costner', 2),
(2, '¿En qué año se estrenó "Jurassic Park"?', '1991', '1993', '1995', '1997', 2),
(2, '¿Cuál es el nombre real de Batman?', 'Clark Kent', 'Bruce Wayne', 'Peter Parker', 'Tony Stark', 2),
(2, '¿Quién dirigió "Inception"?', 'David Fincher', 'Christopher Nolan', 'Denis Villeneuve', 'Zack Snyder', 2),
(2, '¿Cuál fue la primera película de Marvel Cinematic Universe?', 'Thor', 'Iron Man', 'Capitán América', 'Hulk', 2),
(2, '¿En qué película aparece el personaje de Hannibal Lecter?', 'Seven', 'El Silencio de los Corderos', 'Psicosis', 'El Resplandor', 2),
(2, '¿Quién interpretó a Vito Corleone en "El Padrino"?', 'Al Pacino', 'Robert De Niro', 'Marlon Brando', 'James Caan', 3),
(2, '¿Cuál es la saga cinematográfica más taquillera?', 'Harry Potter', 'Marvel', 'Star Wars', 'Fast & Furious', 2),
(2, '¿En qué año se celebraron los primeros premios Oscar?', '1927', '1929', '1931', '1933', 2),
(2, '¿Quién dirigió "Casablanca"?', 'Billy Wilder', 'John Huston', 'Michael Curtiz', 'Frank Capra', 3),
(2, '¿Cuál es el nombre del hobbit protagonista?', 'Gandalf', 'Frodo', 'Sam', 'Bilbo', 2),
(2, '¿En qué película aparece la canción "My Heart Will Go On"?', 'El Fantasma de la Ópera', 'Titanic', 'Romeo y Julieta', 'Ghost', 2),
(2, '¿Quién interpretó a Neo en Matrix?', 'Brad Pitt', 'Keanu Reeves', 'Will Smith', 'Leonardo DiCaprio', 2),
(2, '¿Cuál es la película de Disney más taquillera?', 'El Rey León', 'Frozen', 'Los Increíbles', 'Toy Story 4', 2),
(2, '¿En qué año se estrenó "Blade Runner"?', '1980', '1982', '1984', '1986', 2),
(2, '¿Quién dirigió "Taxi Driver"?', 'Francis Ford Coppola', 'Martin Scorsese', 'Brian De Palma', 'William Friedkin', 2),
(2, '¿Cuál es el verdadero nombre de Scarlett Johansson en Los Vengadores?', 'Natasha Romanoff', 'Wanda Maximoff', 'Maria Hill', 'Pepper Potts', 1),
(2, '¿En qué película aparece el personaje de Clarice Starling?', 'Seven', 'El Silencio de los Corderos', 'Zodiac', 'Primal Fear', 2),
(2, '¿Quién compuso la música de "Star Wars"?', 'Hans Zimmer', 'John Williams', 'Ennio Morricone', 'Danny Elfman', 2),
(2, '¿Cuál fue la última película de Heath Ledger?', 'El Caballero Oscuro', 'Brokeback Mountain', 'El Imaginario del Dr. Parnassus', 'Lords of Dogtown', 3),
(2, '¿En qué película aparece la famosa escena de la ducha?', 'El Resplandor', 'Psicosis', 'El Exorcista', 'Halloween', 2),
(2, '¿Cuál es la trilogía dirigida por Peter Jackson?', 'Matrix', 'El Señor de los Anillos', 'Mad Max', 'Regreso al Futuro', 2),
(2, '¿Qué banda lanzó el álbum "The Dark Side of the Moon"?', 'The Beatles', 'Led Zeppelin', 'Pink Floyd', 'Queen', 3),
(2, '¿Cuál es el nombre real de Lady Gaga?', 'Stefani Germanotta', 'Madonna Ciccone', 'Alecia Moore', 'Destiny Hope', 1),
(2, '¿En qué año murió Michael Jackson?', '2007', '2009', '2011', '2013', 2),
(2, '¿Cuál es la canción más escuchada en Spotify?', 'Shape of You', 'Blinding Lights', 'Someone You Loved', 'Sunflower', 2),
(2, '¿Qué instrumento tocaba Freddie Mercury?', 'Guitarra', 'Batería', 'Piano', 'Bajo', 3),
(2, '¿Cuál fue el primer sencillo de The Beatles que llegó al #1?', 'Love Me Do', 'Please Please Me', 'From Me to You', 'She Loves You', 2),
(2, '¿En qué ciudad nació Elvis Presley?', 'Memphis', 'Nashville', 'Tupelo', 'Nueva Orleans', 3),
(2, '¿Cuál es el álbum más vendido de todos los tiempos?', 'Back in Black', 'Thriller', 'The Dark Side of the Moon', 'Abbey Road', 2),
(2, '¿Qué banda escribió "Bohemian Rhapsody"?', 'Led Zeppelin', 'Queen', 'The Who', 'Deep Purple', 2),
(2, '¿En qué año se separaron The Beatles?', '1968', '1970', '1972', '1974', 2),
(2, '¿Cuál es el nombre real de Bono de U2?', 'Paul David Hewson', 'David Evans', 'Adam Clayton', 'Larry Mullen', 1),
(2, '¿Qué cantante es conocida como "The Queen of Pop"?', 'Whitney Houston', 'Madonna', 'Mariah Carey', 'Céline Dion', 2),
(2, '¿En qué década surgió el rock and roll?', '1940s', '1950s', '1960s', '1970s', 2),
(2, '¿Cuál es el festival de música más grande del mundo?', 'Coachella', 'Glastonbury', 'Rock in Rio', 'Tomorrowland', 3),
(2, '¿Qué rapero tiene más premios Grammy?', 'Eminem', 'Jay-Z', 'Kanye West', 'Drake', 2),
(2, '¿En qué año se lanzó el primer iPod?', '1999', '2001', '2003', '2005', 2),
(2, '¿Cuál es la canción más larga de los Beatles?', 'Hey Jude', 'A Day in the Life', 'I Want You', 'Revolution 9', 4),
(2, '¿Qué instrumento es característico del blues?', 'Violín', 'Armónica', 'Flauta', 'Trompeta', 2),
(2, '¿En qué ciudad se originó el jazz?', 'Chicago', 'Nueva York', 'Nueva Orleans', 'Memphis', 3),
(2, '¿Cuál es el nombre real de Elton John?', 'Reginald Dwight', 'David Jones', 'Farrokh Bulsara', 'Gordon Sumner', 1),
(2, '¿Qué banda lanzó el álbum "Nevermind"?', 'Pearl Jam', 'Nirvana', 'Soundgarden', 'Alice in Chains', 2),
(2, '¿En qué año murió John Lennon?', '1978', '1980', '1982', '1984', 2),
(2, '¿Cuál es la voz más aguda en un coro?', 'Alto', 'Soprano', 'Tenor', 'Bajo', 2),
(2, '¿Qué género musical creó Bob Marley?', 'Calipso', 'Reggae', 'Ska', 'Dancehall', 2),
(2, '¿En qué década surgió el punk rock?', '1960s', '1970s', '1980s', '1990s', 2),
(2, '¿Cuál es la guitarra más cara del mundo?', 'Fender Stratocaster', 'Gibson Les Paul', 'Reach out to Asia', 'Blackie', 3),
(2, '¿Qué cantante interpretó "I Will Always Love You"?', 'Mariah Carey', 'Whitney Houston', 'Céline Dion', 'Aretha Franklin', 2),
(2, '¿En qué año se fundó MTV?', '1979', '1981', '1983', '1985', 2),
(2, '¿Cuál es el nombre de la guitarra de B.B. King?', 'Lucille', 'Stella', 'Rosita', 'Blackie', 1),
(2, '¿Qué banda lanzó "Hotel California"?', 'Fleetwood Mac', 'Eagles', 'The Doors', 'Creedence', 2),
(2, '¿En qué serie aparece el personaje Walter White?', 'Lost', 'Breaking Bad', 'The Sopranos', 'Game of Thrones', 2),
(2, '¿Cuál es la serie más vista de Netflix?', 'Stranger Things', 'La Casa de Papel', 'Squid Game', 'Bridgerton', 3),
(2, '¿En qué año se estrenó "Friends"?', '1992', '1994', '1996', '1998', 2),
(2, '¿Cuál es el nombre del café en "Friends"?', 'Central Perk', 'Coffee Bean', 'Starbucks', 'Café Nervosa', 1),
(2, '¿En qué serie aparece Tyrion Lannister?', 'The Witcher', 'Game of Thrones', 'Vikings', 'The Crown', 2),
(2, '¿Cuántas temporadas tiene "The Office" (US)?', '7', '8', '9', '10', 3),
(2, '¿En qué ciudad transcurre "Sex and the City"?', 'Los Ángeles', 'Nueva York', 'Chicago', 'Miami', 2),
(2, '¿Cuál es el nombre del protagonista de "House"?', 'Gregory House', 'John House', 'Hugh House', 'James House', 1),
(2, '¿En qué década se estrenó "Los Simpson"?', '1980s', '1990s', '2000s', '2010s', 1),
(2, '¿Cuál es la serie de ciencia ficción más larga?', 'Star Trek', 'Doctor Who', 'The X-Files', 'Stargate', 2),
(2, '¿En qué serie aparece el personaje Sheldon Cooper?', 'Friends', 'How I Met Your Mother', 'The Big Bang Theory', 'Community', 3),
(2, '¿Cuál es el nombre real de Heisenberg?', 'Jesse Pinkman', 'Walter White', 'Saul Goodman', 'Mike Ehrmantraut', 2),
(2, '¿En qué año terminó "Game of Thrones"?', '2017', '2018', '2019', '2020', 3),
(2, '¿Cuál es la serie animada más longeva?', 'Los Simpson', 'South Park', 'Family Guy', 'Futurama', 1),
(2, '¿En qué serie aparece el agente Fox Mulder?', 'CSI', 'The X-Files', 'Criminal Minds', 'NCIS', 2),
(2, '¿Cuál es el nombre del dragón de Daenerys más grande?', 'Viserion', 'Rhaegal', 'Drogon', 'Balerion', 3),
(2, '¿En qué serie aparece el bar "Cheers"?', 'Cheers', 'Frasier', 'How I Met Your Mother', 'Todas las anteriores', 1),
(2, '¿Cuántos episodios tiene la primera temporada de "Stranger Things"?', '6', '8', '10', '12', 2),
(2, '¿En qué serie aparece el personaje Tyrion Lannister?', 'Vikings', 'Game of Thrones', 'The Witcher', 'The Last Kingdom', 2),
(2, '¿Cuál es el apellido de Homer Simpson?', 'Johnson', 'Simpson', 'Thompson', 'Jackson', 2),
(2, '¿En qué serie aparece el número 4815162342?', 'Prison Break', 'Lost', '24', 'Heroes', 2),
(2, '¿Cuál es la profesión de Dexter Morgan?', 'Policía', 'Forense', 'Detective', 'Médico', 2),
(2, '¿En qué década transcurre "Stranger Things"?', '1970s', '1980s', '1990s', '2000s', 2),
(2, '¿Cuál es el nombre del hospital en "Greys Anatomy"?', 'Seattle Grace', 'General Hospital', 'Sacred Heart', 'County General', 1),
(2, '¿En qué serie aparece el café "Central Perk"?', 'Seinfeld', 'Friends', 'How I Met Your Mother', 'Frasier', 2),
(2, '¿Cuál es el videojuego más vendido de la historia?', 'Tetris', 'Minecraft', 'GTA V', 'Wii Sports', 2),
(2, '¿En qué año se lanzó el primer Super Mario Bros?', '1983', '1985', '1987', '1989', 2),
(2, '¿Cuál es el nombre del protagonista de The Legend of Zelda?', 'Zelda', 'Link', 'Ganondorf', 'Navi', 2),
(2, '¿Qué empresa creó la consola PlayStation?', 'Nintendo', 'Sony', 'Microsoft', 'Sega', 2),
(2, '¿En qué año se lanzó Pac-Man?', '1978', '1980', '1982', '1984', 2),
(2, '¿Cuál es el nombre del protagonista de Half-Life?', 'Gordon Freeman', 'John Freeman', 'Alex Vance', 'Barney Calhoun', 1),
(2, '¿Qué significa "NPC" en videojuegos?', 'Non-Player Character', 'New Player Character', 'Next Player Character', 'No Player Character', 1),
(2, '¿En qué videojuego aparece el personaje Master Chief?', 'Call of Duty', 'Halo', 'Gears of War', 'Destiny', 2),
(2, '¿Cuál es la consola más vendida de Nintendo?', 'NES', 'Game Boy', 'Nintendo DS', 'Wii', 3),
(2, '¿En qué año se lanzó World of Warcraft?', '2002', '2004', '2006', '2008', 2),
(2, '¿Cuál es el nombre del fontanero de Nintendo?', 'Luigi', 'Mario', 'Wario', 'Waluigi', 2),
(2, '¿Qué videojuego popularizó el género Battle Royale?', 'PUBG', 'Fortnite', 'Apex Legends', 'H1Z1', 1),
(2, '¿En qué videojuego aparecen los Creepers?', 'Terraria', 'Minecraft', 'Roblox', 'Fortnite', 2),
(2, '¿Cuál es la saga de videojuegos de terror más famosa?', 'Silent Hill', 'Resident Evil', 'Dead Space', 'Fatal Frame', 2),
(2, '¿En qué plataforma se popularizó el streaming de videojuegos?', 'YouTube', 'Twitch', 'Facebook', 'TikTok', 2);


INSERT INTO preguntas (categoria_id, pregunta, respuesta_1, respuesta_2, respuesta_3, respuesta_4, respuesta_correcta) VALUES
(3, '¿En qué año comenzó la Segunda Guerra Mundial?', '1938', '1939', '1940', '1941', 2),
(3, '¿Quién fue el primer presidente de Estados Unidos?', 'Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin', 3),
(3, '¿En qué año cayó el Muro de Berlín?', '1987', '1988', '1989', '1990', 3),
(3, '¿En qué año llegó Cristóbal Colón a América?', '1490', '1491', '1492', '1493', 3),
(3, '¿Quién fue el líder de la Alemania Nazi?', 'Heinrich Himmler', 'Joseph Goebbels', 'Adolf Hitler', 'Hermann Göring', 3),
(3, '¿En qué año terminó la Primera Guerra Mundial?', '1917', '1918', '1919', '1920', 2),
(3, '¿Cuál fue la primera civilización de la historia?', 'Egipcia', 'Mesopotámica', 'China', 'India', 2),
(3, '¿En qué año se firmó la Declaración de Independencia de EE.UU.?', '1774', '1775', '1776', '1777', 3),
(3, '¿Quién fue conocido como "El Conquistador"?', 'Julio César', 'Alejandro Magno', 'Napoleón Bonaparte', 'Carlomagno', 2),
(3, '¿En qué siglo vivió Leonardo da Vinci?', 'XIV', 'XV', 'XVI', 'XVII', 3),
(3, '¿Cuál fue el imperio más extenso de la historia?', 'Romano', 'Mongol', 'Británico', 'Otomano', 3),
(3, '¿En qué año se fundó Roma?', '753 a.C.', '776 a.C.', '800 a.C.', '509 a.C.', 1),
(3, '¿Quién escribió "El Príncipe"?', 'Platón', 'Aristóteles', 'Maquiavelo', 'Hobbes', 3),
(3, '¿En qué batalla fue derrotado Napoleón definitivamente?', 'Austerlitz', 'Waterloo', 'Leipzig', 'Trafalgar', 2),
(3, '¿Cuál fue la dinastía china más larga?', 'Han', 'Tang', 'Zhou', 'Qing', 3),
(3, '¿En qué año se descubrió América para los europeos?', '1490', '1492', '1494', '1496', 2),
(3, '¿Quién fue el primer emperador romano?', 'Julio César', 'Augusto', 'Nerón', 'Trajano', 2),
(3, '¿En qué siglo ocurrió la Revolución Francesa?', 'XVII', 'XVIII', 'XIX', 'XX', 2),
(3, '¿Cuál fue la capital del Imperio Bizantino?', 'Roma', 'Atenas', 'Constantinopla', 'Alejandría', 3),
(3, '¿En qué año se produjo la Revolución Rusa?', '1905', '1917', '1919', '1921', 2),
(3, '¿Quién unificó Alemania en el siglo XIX?', 'Otto von Bismarck', 'Wilhelm II', 'Frederick III', 'Ludwig II', 1),
(3, '¿En qué guerra participó Joan of Arc?', 'Guerra de los Cien Años', 'Guerra de las Rosas', 'Guerra de Sucesión', 'Cruzadas', 1),
(3, '¿Cuál fue la primera universidad del mundo?', 'Oxford', 'Bolonia', 'Salerno', 'Al-Azhar', 4),
(3, '¿En qué año se abolió la esclavitud en Estados Unidos?', '1863', '1865', '1867', '1869', 2),
(3, '¿Quién fue el faraón que construyó la Gran Pirámide?', 'Tutankamón', 'Ramsés II', 'Keops', 'Akhenatón', 3),
(3, '¿En qué siglo vivió Marco Polo?', 'XII', 'XIII', 'XIV', 'XV', 2),
(3, '¿Cuál fue la causa del hundimiento del Titanic?', 'Tormenta', 'Iceberg', 'Explosión', 'Colisión', 2),
(3, '¿En qué año se creó la ONU?', '1944', '1945', '1946', '1947', 2),
(3, '¿Quién fue el último zar de Rusia?', 'Alejandro III', 'Nicolás II', 'Pavel I', 'Alejandro II', 2),
(3, '¿En qué ciudad se firmó la paz que terminó la Primera Guerra Mundial?', 'París', 'Versalles', 'Londres', 'Ginebra', 2),
(3, '¿Cuál fue la pandemia más mortífera del siglo XIV?', 'Cólera', 'Viruela', 'Peste Negra', 'Gripe', 3),
(3, '¿En qué año se produjo la caída de Constantinopla?', '1451', '1453', '1455', '1457', 2),
(3, '¿Quién fue conocido como "El Rey Sol"?', 'Luis XIII', 'Luis XIV', 'Luis XV', 'Luis XVI', 2),
(3, '¿En qué siglo se produjeron las Cruzadas?', 'X-XII', 'XI-XIII', 'XII-XIV', 'XIII-XV', 2),
(3, '¿Cuál fue la civilización precolombina más avanzada?', 'Azteca', 'Maya', 'Inca', 'Olmeca', 2),
(3, '¿Qué imperio construyó Machu Picchu?', 'Azteca', 'Maya', 'Inca', 'Olmeca', 3),
(3, '¿En qué año se independizó México?', '1810', '1821', '1824', '1836', 2),
(3, '¿Quién fue el libertador de Venezuela?', 'José de San Martín', 'Simón Bolívar', 'Bernardo O Higgins', 'Antonio José de Sucre', 2),
(3, '¿En qué año llegaron los españoles a México?', '1517', '1519', '1521', '1523', 2),
(3, '¿Cuál fue la capital del Imperio Azteca?', 'Cuzco', 'Tenochtitlán', 'Chichén Itzá', 'Palenque', 2),
(3, '¿En qué año se independizó Argentina?', '1810', '1816', '1820', '1825', 2),
(3, '¿Quién conquistó el Imperio Inca?', 'Hernán Cortés', 'Francisco Pizarro', 'Diego de Almagro', 'Vasco de Balboa', 2),
(3, '¿En qué año se independizó Brasil?', '1820', '1822', '1824', '1826', 2),
(3, '¿Cuál fue la primera ciudad fundada por los españoles en América?', 'La Habana', 'Santo Domingo', 'Veracruz', 'Cartagena', 2),
(3, '¿En qué año llegó Cortés a México?', '1517', '1519', '1521', '1523', 2),
(3, '¿Quién fue el último emperador azteca?', 'Moctezuma II', 'Cuauhtémoc', 'Cuitláhuac', 'Itzcoatl', 2),
(3, '¿En qué año se produjo la Revolución Mexicana?', '1910', '1912', '1914', '1916', 1),
(3, '¿Cuál fue la ruta que siguió Colón en su primer viaje?', 'Atlántico Norte', 'Atlántico Sur', 'Atlántico Central', 'Mediterráneo', 3),
(3, '¿En qué isla desembarcó primero Colón?', 'Cuba', 'Jamaica', 'Guanahani', 'Puerto Rico', 3),
(3, '¿Quién fue el primer virrey del Perú?', 'Francisco Pizarro', 'Blasco Núñez Vela', 'Antonio de Mendoza', 'Diego López de Zúñiga', 2),
(3, '¿En qué año se fundó Buenos Aires definitivamente?', '1536', '1580', '1620', '1650', 2),
(3, '¿Cuál fue la batalla decisiva de la independencia de Chile?', 'Chacabuco', 'Maipú', 'Rancagua', 'Cancha Rayada', 2),
(3, '¿En qué año murió Simón Bolívar?', '1828', '1830', '1832', '1834', 2),
(3, '¿Cuál fue la guerra entre Argentina y Reino Unido?', 'Guerra del Pacífico', 'Guerra de las Malvinas', 'Guerra del Chaco', 'Guerra de la Triple Alianza', 2),
(3, '¿En qué año se inauguró el Canal de Panamá?', '1912', '1914', '1916', '1918', 2),
(3, '¿Quién fue conocido como "El Padre de la Patria" en Argentina?', 'San Martín', 'Belgrano', 'Moreno', 'Rivadavia', 1),
(3, '¿En qué batalla se selló la independencia del Perú?', 'Junín', 'Ayacucho', 'Pichincha', 'Boyacá', 2),
(3, '¿Cuál fue la primera constitución de México?', 'Constitución de 1824', 'Constitución de 1857', 'Constitución de 1917', 'Leyes de Reforma', 1),
(3, '¿En qué año se abolió la esclavitud en Brasil?', '1885', '1888', '1890', '1892', 2),
(3, '¿Quién fue el primer presidente de Estados Unidos nacido en el siglo XX?', 'Theodore Roosevelt', 'John F. Kennedy', 'Lyndon Johnson', 'Richard Nixon', 2),
(3, '¿Cuánto duró la Guerra de los Cien Años?', '100 años', '116 años', '130 años', '145 años', 2),
(3, '¿En qué año comenzó la Guerra de Vietnam?', '1955', '1964', '1968', '1970', 1),
(3, '¿Cuál fue la batalla más sangrienta de la Guerra Civil Americana?', 'Bull Run', 'Antietam', 'Gettysburg', 'Shiloh', 3),
(3, '¿En qué año terminó la Guerra Fría?', '1989', '1991', '1993', '1995', 2),
(3, '¿Cuál fue la causa inmediata de la Primera Guerra Mundial?', 'Invasión de Polonia', 'Asesinato del Archiduque Francisco Fernando', 'Hundimiento del Lusitania', 'Crisis de los Balcanes', 2),
(3, '¿En qué batalla derrotó Wellington a Napoleón?', 'Austerlitz', 'Jena', 'Waterloo', 'Leipzig', 3),
(3, '¿Cuál fue la guerra más corta de la historia?', 'Guerra Anglo-Zanzibar', 'Guerra del Fútbol', 'Guerra de los Seis Días', 'Guerra de las Malvinas', 1),
(3, '¿En qué año se produjo Pearl Harbor?', '1940', '1941', '1942', '1943', 2),
(3, '¿Cuál fue el último país en unirse a los Aliados en la Segunda Guerra Mundial?', 'Estados Unidos', 'Unión Soviética', 'Brasil', 'Japón', 3),
(3, '¿En qué guerra se usaron por primera vez las armas químicas?', 'Guerra Franco-Prusiana', 'Primera Guerra Mundial', 'Segunda Guerra Mundial', 'Guerra de Corea', 2),
(3, '¿Cuál fue la operación de desembarco en Normandía?', 'Operación Barbarroja', 'Operación Overlord', 'Operación Market Garden', 'Operación Bagration', 2),
(3, '¿En qué año se produjo la Crisis de los Misiles en Cuba?', '1960', '1962', '1964', '1966', 2),
(3, '¿Cuál fue la guerra civil más larga del siglo XX?', 'Guerra Civil Española', 'Guerra Civil China', 'Guerra Civil Rusa', 'Guerra Civil Guatemalteca', 4),
(3, '¿En qué año cayó Saigón?', '1973', '1975', '1977', '1979', 2),
(3, '¿Cuál fue la batalla naval más grande de la Primera Guerra Mundial?', 'Jutlandia', 'Dogger Bank', 'Coronel', 'Falklands', 1),
(3, '¿En qué guerra participó el Barón Rojo?', 'Guerra Franco-Prusiana', 'Primera Guerra Mundial', 'Segunda Guerra Mundial', 'Guerra de los Boers', 2),
(3, '¿Cuál fue el primer país en declarar la guerra en 1939?', 'Francia', 'Reino Unido', 'Polonia', 'Australia', 2),
(3, '¿En qué año se firmó el Tratado de Versalles?', '1918', '1919', '1920', '1921', 2),
(3, '¿Cuál fue la operación alemana de invasión a la Unión Soviética?', 'Operación Sealion', 'Operación Barbarroja', 'Operación Citadel', 'Operación Typhoon', 2),
(3, '¿En qué guerra se produjo la Batalla de Stalingrado?', 'Primera Guerra Mundial', 'Segunda Guerra Mundial', 'Guerra Fría', 'Guerra Civil Rusa', 2),
(3, '¿Quién fue conocido como "La Doncella de Orleans"?', 'María Antonieta', 'Juana de Arco', 'Isabel la Católica', 'Catalina la Grande', 2),
(3, '¿Cuál fue el nombre real de Tutankamón?', 'Tutankhaten', 'Amenhotep', 'Akhenaten', 'Ramesses', 1),
(3, '¿Quién escribió "El Arte de la Guerra"?', 'Confucio', 'Lao-Tse', 'Sun Tzu', 'Mencio', 3),
(3, '¿Cuál fue el emperador romano que legalizó el cristianismo?', 'Augusto', 'Constantino', 'Teodosio', 'Justiniano', 2),
(3, '¿Quién fue conocido como "El Azote de Dios"?', 'Gengis Khan', 'Atila', 'Tamerlán', 'Alarico', 2),
(3, '¿Cuál fue la reina egipcia más famosa?', 'Nefertiti', 'Cleopatra', 'Hatshepsut', 'Nefertari', 2),
(3, '¿Quién fue el filósofo griego maestro de Alejandro Magno?', 'Platón', 'Aristóteles', 'Sócrates', 'Diógenes', 2),
(3, '¿Cuál fue el nombre del caballo de Alejandro Magno?', 'Bucéfalo', 'Rocinante', 'Babieca', 'Pegaso', 1),
(3, '¿Quién fue conocido como "El Pequeño Cabo"?', 'Hitler', 'Napoleón', 'Mussolini', 'Franco', 2),
(3, '¿Cuál fue la esposa de Napoleón?', 'Josefina', 'María Antonieta', 'Catalina', 'Isabel', 1),
(3, '¿Quién fue el líder de la Revolución Cubana?', 'Che Guevara', 'Fidel Castro', 'Camilo Cienfuegos', 'Raúl Castro', 2),
(3, '¿Cuál fue el nombre de pila de Gandhi?', 'Rajiv', 'Mohandas', 'Jawaharlal', 'Indira', 2),
(3, '¿Quién fue conocido como "Espartaco"?', 'Gladiador romano', 'Emperador romano', 'General cartaginés', 'Filósofo griego', 1),
(3, '¿Cuál fue el presidente de EE.UU. durante la Guerra Civil?', 'Andrew Johnson', 'Abraham Lincoln', 'Ulysses Grant', 'James Buchanan', 2),
(3, '¿Quién fue el primer ministro británico durante la Segunda Guerra Mundial?', 'Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden', 2),
(3, '¿Cuál fue el explorador que dio la primera vuelta al mundo?', 'Cristóbal Colón', 'Fernando de Magallanes', 'Vasco de Gama', 'James Cook', 2),
(3, '¿Quién fue conocido como "El Libertador"?', 'San Martín', 'Simón Bolívar', 'O Higgins', 'Sucre', 2),
(3, '¿Cuál fue la emperatriz de Francia esposa de Napoleón III?', 'Eugenia de Montijo', 'Josefina', 'María Luisa', 'Ana de Austria', 1),
(3, '¿Quién fue el líder de la Reforma Protestante?', 'Juan Calvino', 'Martín Lutero', 'Zwinglio', 'Erasmo', 2),
(3, '¿Cuál fue el faraón que trasladó la capital a Amarna?', 'Tutankamón', 'Akhenatón', 'Ramsés II', 'Seti I', 2);

INSERT INTO preguntas (categoria_id, pregunta, respuesta_1, respuesta_2, respuesta_3, respuesta_4, respuesta_correcta) VALUES
(4, '¿Cuál es la velocidad de la luz en el vacío?', '299,792,458 m/s', '300,000,000 m/s', '298,000,000 m/s', '301,000,000 m/s', 1),
(4, '¿Quién propuso la teoría de la relatividad?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking', 2),
(4, '¿Cuál es la unidad de medida de la fuerza?', 'Joule', 'Newton', 'Pascal', 'Watt', 2),
(4, '¿Qué ley establece que toda acción tiene una reacción?', 'Primera Ley de Newton', 'Segunda Ley de Newton', 'Tercera Ley de Newton', 'Ley de Gravitación Universal', 3),
(4, '¿Cuál es la constante gravitacional aproximada?', '9.8 m/s²', '6.67 × 10⁻¹¹ N⋅m²/kg²', '3 × 10⁸ m/s', '1.6 × 10⁻¹⁹ C', 2),
(4, '¿Qué partícula subatómica tiene carga negativa?', 'Protón', 'Neutrón', 'Electrón', 'Positrón', 3),
(4, '¿Cuál es la temperatura del cero absoluto?', '-273.15°C', '-300°C', '-250°C', '-200°C', 1),
(4, '¿Qué tipo de ondas son las ondas de radio?', 'Mecánicas', 'Electromagnéticas', 'Sonoras', 'Sísmicas', 2),
(4, '¿Cuál es la ecuación más famosa de Einstein?', 'F=ma', 'E=mc²', 'PV=nRT', 'F=kx', 2),
(4, '¿Qué mide un barómetro?', 'Temperatura', 'Humedad', 'Presión atmosférica', 'Velocidad del viento', 3),
(4, '¿Cuál es la unidad de medida de la energía?', 'Newton', 'Watt', 'Joule', 'Pascal', 3),
(4, '¿Qué científico descubrió la radioactividad?', 'Marie Curie', 'Henri Becquerel', 'Pierre Curie', 'Ernest Rutherford', 2),
(4, '¿Cuál es el estado de la materia más abundante en el universo?', 'Sólido', 'Líquido', 'Gas', 'Plasma', 4),
(4, '¿Qué ley explica el comportamiento de los gases ideales?', 'Ley de Boyle', 'Ley de Charles', 'Ley de Gay-Lussac', 'Ley de los gases ideales', 4),
(4, '¿Cuál es la partícula que da masa a otras partículas?', 'Fotón', 'Bosón de Higgs', 'Neutrino', 'Muón', 2),
(4, '¿Qué fenómeno explica por qué el cielo es azul?', 'Reflexión', 'Refracción', 'Dispersión de Rayleigh', 'Difracción', 3),
(4, '¿Cuál es la unidad de medida de la resistencia eléctrica?', 'Ampere', 'Volt', 'Ohm', 'Watt', 3),
(4, '¿Qué tipo de lente corrige la miopía?', 'Convexa', 'Cóncava', 'Cilíndrica', 'Bifocal', 2),
(4, '¿Cuál es la fórmula de la segunda ley de Newton?', 'F=ma', 'E=mc²', 'P=mv', 'W=Fd', 1),
(4, '¿Qué mide un voltímetro?', 'Corriente', 'Voltaje', 'Resistencia', 'Potencia', 2),
(4, '¿Cuál es el principio de Arquímedes?', 'Todo cuerpo sumergido experimenta un empuje', 'La energía se conserva', 'La materia no se crea ni se destruye', 'Todo en movimiento tiende a seguir en movimiento', 1),
(4, '¿Qué partícula no tiene masa?', 'Electrón', 'Protón', 'Neutrón', 'Fotón', 4),
(4, '¿Cuál es la unidad de frecuencia?', 'Metro', 'Segundo', 'Hertz', 'Newton', 3),
(4, '¿Qué efecto describe la curvatura del espacio-tiempo?', 'Efecto fotoeléctrico', 'Efecto Doppler', 'Relatividad general', 'Efecto Compton', 3),
(4, '¿Cuál es la constante de Planck aproximadamente?', '6.626 × 10⁻³⁴ J⋅s', '9.8 m/s²', '3 × 10⁸ m/s', '1.6 × 10⁻¹⁹ C', 1),
(4, '¿Cuál es el elemento químico más abundante en el universo?', 'Oxígeno', 'Hidrógeno', 'Carbono', 'Helio', 2),
(4, '¿Cuál es el símbolo químico del oro?', 'Go', 'Au', 'Ag', 'Or', 2),
(4, '¿Cuántos elementos hay en la tabla periódica actualmente?', '103', '115', '118', '120', 3),
(4, '¿Qué gas representa aproximadamente el 78% de la atmósfera terrestre?', 'Oxígeno', 'Dióxido de carbono', 'Nitrógeno', 'Argón', 3),
(4, '¿Cuál es la fórmula química del agua?', 'H₂O', 'HO', 'H₂O₂', 'OH', 1),
(4, '¿Quién creó la tabla periódica moderna?', 'Antoine Lavoisier', 'Dmitri Mendeléyev', 'John Dalton', 'Marie Curie', 2),
(4, '¿Cuál es el pH del agua pura?', '6', '7', '8', '9', 2),
(4, '¿Qué tipo de enlace se forma entre un metal y un no metal?', 'Covalente', 'Iónico', 'Metálico', 'Van der Waals', 2),
(4, '¿Cuál es el elemento más electronegativo?', 'Oxígeno', 'Flúor', 'Cloro', 'Nitrógeno', 2),
(4, '¿Qué partículas se encuentran en el núcleo atómico?', 'Electrones y protones', 'Protones y neutrones', 'Solo protones', 'Electrones y neutrones', 2),
(4, '¿Cuál es la unidad de cantidad de sustancia?', 'Gramo', 'Mol', 'Litro', 'Átomo', 2),
(4, '¿Qué número indica la cantidad de protones en un átomo?', 'Número de masa', 'Número atómico', 'Número de neutrones', 'Número cuántico', 2),
(4, '¿Cuál es la fórmula del dióxido de carbono?', 'CO', 'CO₂', 'C₂O', 'CHO', 2),
(4, '¿Qué proceso convierte un líquido en gas?', 'Condensación', 'Evaporación', 'Sublimación', 'Fusión', 2),
(4, '¿Cuál es el elemento más pesado que se produce naturalmente?', 'Plutonio', 'Uranio', 'Radio', 'Torio', 2),
(4, '¿Qué tipo de reacción absorbe energía?', 'Exotérmica', 'Endotérmica', 'Catalítica', 'Redox', 2),
(4, '¿Cuál es la fórmula del amoníaco?', 'NH₃', 'NH₄', 'N₂H', 'NH₂', 1),
(4, '¿Qué gas noble es más abundante en la atmósfera?', 'Helio', 'Neón', 'Argón', 'Kriptón', 3),
(4, '¿Cuál es el isótopo más común del carbono?', 'Carbono-12', 'Carbono-13', 'Carbono-14', 'Carbono-11', 1),
(4, '¿Qué mide la escala de pH?', 'Temperatura', 'Acidez/Basicidad', 'Densidad', 'Concentración', 2),
(4, '¿Cuál es la configuración electrónica del helio?', '1s¹', '1s²', '2s¹', '1s²2s¹', 2),
(4, '¿Qué catalizador acelera las reacciones biológicas?', 'Enzimas', 'Hormonas', 'Vitaminas', 'Minerales', 1),
(4, '¿Cuál es la fórmula del metano?', 'CH₄', 'C₂H₄', 'C₂H₆', 'CH₂', 1),
(4, '¿Qué proceso separa mezclas por diferencia de puntos de ebullición?', 'Filtración', 'Destilación', 'Decantación', 'Cristalización', 2),
(4, '¿Cuál es la masa atómica aproximada del carbono?', '6', '12', '14', '16', 2),
(4, '¿Cuántos huesos tiene el cuerpo humano adulto?', '198', '206', '214', '220', 2),
(4, '¿Cuál es la unidad básica de la vida?', 'Tejido', 'Célula', 'Órgano', 'Átomo', 2),
(4, '¿Qué orgánulo contiene el ADN en las células eucariotas?', 'Mitocondria', 'Núcleo', 'Ribosoma', 'Retículo endoplasmático', 2),
(4, '¿Cuántas cámaras tiene el corazón humano?', '2', '3', '4', '5', 3),
(4, '¿Qué proceso realizan las plantas para producir energía?', 'Respiración', 'Fotosíntesis', 'Fermentación', 'Digestión', 2),
(4, '¿Cuál es el órgano más grande del cuerpo humano?', 'Hígado', 'Cerebro', 'Pulmones', 'Piel', 4),
(4, '¿Qué tipo de sangre es el donante universal?', 'A+', 'B-', 'AB+', 'O-', 4),
(4, '¿Cuántos cromosomas tiene el ser humano?', '44', '46', '48', '50', 2),
(4, '¿Qué vitamina produce la piel con la exposición solar?', 'Vitamina A', 'Vitamina C', 'Vitamina D', 'Vitamina E', 3),
(4, '¿Cuál es el músculo más fuerte del cuerpo humano?', 'Bíceps', 'Cuádriceps', 'Masetero', 'Glúteo mayor', 3),
(4, '¿Qué animal es conocido por su capacidad de regeneración?', 'Salamandra', 'Estrella de mar', 'Planaria', 'Todos los anteriores', 4),
(4, '¿Cuánto tiempo vive un glóbulo rojo?', '30 días', '60 días', '120 días', '180 días', 3),
(4, '¿Qué hormona regula el azúcar en la sangre?', 'Adrenalina', 'Insulina', 'Tiroxina', 'Cortisol', 2),
(4, '¿Cuál es el animal más rápido del mundo?', 'Guepardo', 'Halcón peregrino', 'Antílope', 'Atún', 2),
(4, '¿Qué parte del cerebro controla el equilibrio?', 'Cerebro', 'Cerebelo', 'Tronco encefálico', 'Hipotálamo', 2),
(4, '¿Cuántos pares de nervios craneales existen?', '10', '12', '14', '16', 2),
(4, '¿Qué gas exhalan las plantas durante la fotosíntesis?', 'Dióxido de carbono', 'Oxígeno', 'Nitrógeno', 'Vapor de agua', 2),
(4, '¿Cuál es el período de gestación del elefante?', '9 meses', '15 meses', '22 meses', '24 meses', 3),
(4, '¿Qué órgano produce la bilis?', 'Páncreas', 'Hígado', 'Vesícula biliar', 'Estómago', 2),
(4, '¿Cuántos dientes tiene un adulto humano normalmente?', '28', '30', '32', '34', 3),
(4, '¿Qué sistema transporta la sangre por el cuerpo?', 'Sistema respiratorio', 'Sistema circulatorio', 'Sistema nervioso', 'Sistema digestivo', 2),
(4, '¿Cuál es la función principal de los riñones?', 'Producir hormonas', 'Filtrar la sangre', 'Digerir alimentos', 'Bombear sangre', 2),
(4, '¿Qué tipo de animal es una ballena?', 'Pez', 'Mamífero', 'Reptil', 'Anfibio', 2),
(4, '¿Cuántos ojos tiene una abeja?', '2', '3', '5', '6', 3),
(4, '¿Qué determina el grupo sanguíneo?', 'Los glóbulos blancos', 'Los antígenos', 'Las plaquetas', 'El plasma', 2),
(4, '¿Cuál es el planeta más cercano al Sol?', 'Venus', 'Mercurio', 'Tierra', 'Marte', 2),
(4, '¿Cuántos planetas hay en nuestro sistema solar?', '7', '8', '9', '10', 2),
(4, '¿Cuál es la estrella más cercana a la Tierra?', 'Alpha Centauri', 'Sirius', 'El Sol', 'Proxima Centauri', 3),
(4, '¿Cuál es el planeta más grande del sistema solar?', 'Saturno', 'Júpiter', 'Neptuno', 'Urano', 2),
(4, '¿Cuánto tiempo tarda la luz del Sol en llegar a la Tierra?', '8 minutos', '1 hora', '1 día', '1 mes', 1),
(4, '¿Cuál es el satélite natural de la Tierra?', 'Fobos', 'Europa', 'Luna', 'Titán', 3),
(4, '¿Qué planeta es conocido como el "Planeta Rojo"?', 'Venus', 'Marte', 'Júpiter', 'Saturno', 2),
(4, '¿Cuál es la galaxia más cercana a la Vía Láctea?', 'Galaxia del Triángulo', 'Galaxia de Andrómeda', 'Nebulosa de Orión', 'Galaxia del Sombrero', 2),
(4, '¿Qué es un agujero negro?', 'Una estrella muy brillante', 'Una región con gravedad extrema', 'Un planeta sin atmósfera', 'Una nebulosa oscura', 2),
(4, '¿Cuántas lunas tiene Júpiter aproximadamente?', '4', '16', '79', '100+', 3),
(4, '¿Qué misión llevó al primer hombre a la Luna?', 'Apollo 10', 'Apollo 11', 'Apollo 12', 'Gemini 7', 2),
(4, '¿Cuál es la temperatura aproximada del Sol?', '6,000°C', '15,000,000°C en el núcleo', '100,000°C', 'Ambas A y B', 4),
(4, '¿Qué planeta tiene los anillos más visibles?', 'Júpiter', 'Saturno', 'Urano', 'Neptuno', 2),
(4, '¿Cuánto dura un año en Marte?', '365 días', '687 días terrestres', '225 días', '12 años terrestres', 2),
(4, '¿Qué es la Estación Espacial Internacional?', 'Un satélite artificial', 'Una base lunar', 'Un laboratorio espacial', 'Una sonda espacial', 3),
(4, '¿Cuál es el valor de π (pi) aproximadamente?', '3.14159', '2.71828', '1.41421', '1.61803', 1),
(4, '¿Quién inventó la World Wide Web?', 'Bill Gates', 'Steve Jobs', 'Tim Berners-Lee', 'Mark Zuckerberg', 3),
(4, '¿Qué significa CPU en informática?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Unit', 'Computer Processing Unit', 1),
(4, '¿Cuál es el teorema más famoso en geometría?', 'Teorema de Tales', 'Teorema de Pitágoras', 'Teorema de Fermat', 'Teorema de Euclides', 2),
(4, '¿En qué sistema numérico trabajan las computadoras?', 'Decimal', 'Binario', 'Hexadecimal', 'Octal', 2),
(4, '¿Cuál es la unidad básica de información en computación?', 'Byte', 'Bit', 'Kilobyte', 'Megabyte', 2),
(4, '¿Qué significa AI en tecnología?', 'Automatic Intelligence', 'Artificial Intelligence', 'Advanced Interface', 'Automated Integration', 2),
(4, '¿Cuántos lados tiene un dodecágono?', '10', '12', '15', '20', 2),
(4, '¿Qué lenguaje de programación desarrolló Python?', 'Guido van Rossum', 'Dennis Ritchie', 'James Gosling', 'Bjarne Stroustrup', 1),
(4, '¿Cuál es la raíz cuadrada de 144?', '11', '12', '13', '14', 2);

INSERT INTO preguntas (categoria_id, pregunta, respuesta_1, respuesta_2, respuesta_3, respuesta_4, respuesta_correcta) VALUES
(5, '¿Quién pintó "La Noche Estrellada"?', 'Pablo Picasso', 'Vincent van Gogh', 'Leonardo da Vinci', 'Claude Monet', 2),
(5, '¿En qué museo se encuentra la Mona Lisa?', 'Museo del Prado', 'Louvre', 'Museo Británico', 'MET', 2),
(5, '¿Quién pintó "Guernica"?', 'Salvador Dalí', 'Pablo Picasso', 'Joan Miró', 'Francisco Goya', 2),
(5, '¿Cuál es la obra más famosa de Leonardo da Vinci?', 'La Última Cena', 'La Mona Lisa', 'El Hombre de Vitruvio', 'Todas son muy famosas', 4),
(5, '¿Qué movimiento artístico fundó Pablo Picasso?', 'Impresionismo', 'Surrealismo', 'Cubismo', 'Expresionismo', 3),
(5, '¿Quién pintó "La persistencia de la memoria"?', 'René Magritte', 'Salvador Dalí', 'Max Ernst', 'André Breton', 2),
(5, '¿En qué siglo vivió Miguel Ángel?', 'XIV', 'XV', 'XVI', 'XVII', 3),
(5, '¿Quién pintó "El Grito"?', 'Edvard Munch', 'Vincent van Gogh', 'Paul Cezanne', 'Henri Matisse', 1),
(5, '¿Cuál es la técnica de pintar con puntos pequeños?', 'Impresionismo', 'Puntillismo', 'Fauvismo', 'Expresionismo', 2),
(5, '¿Quién pintó "Las Meninas"?', 'El Greco', 'Diego Velázquez', 'Francisco Goya', 'Bartolomé Murillo', 2),
(5, '¿En qué museo está "El Nacimiento de Venus"?', 'Uffizi', 'Louvre', 'Prado', 'National Gallery', 1),
(5, '¿Quién fue el líder del movimiento impresionista?', 'Claude Monet', 'Edgar Degas', 'Auguste Renoir', 'Camille Pissarro', 1),
(5, '¿Qué artista se cortó la oreja?', 'Paul Gauguin', 'Vincent van Gogh', 'Henri Toulouse-Lautrec', 'Paul Cezanne', 2),
(5, '¿Cuál es la obra maestra de Sandro Botticelli?', 'La Primavera', 'El Nacimiento de Venus', 'Ambas son igual de famosas', 'La Anunciación', 3),
(5, '¿Quién pintó "American Gothic"?', 'Edward Hopper', 'Grant Wood', 'Georgia O Keeffe', 'Andrew Wyeth', 2),
(5, '¿En qué país nació Pablo Picasso?', 'Francia', 'España', 'Italia', 'Portugal', 2),
(5, '¿Cuál es la pintura más cara jamás vendida?', 'La Mona Lisa', 'Salvator Mundi', 'Los Jugadores de Cartas', 'Intercambio', 2),
(5, '¿Quién pintó "La Gioconda"?', 'Rafael', 'Leonardo da Vinci', 'Miguel Ángel', 'Donatello', 2),
(5, '¿Qué significa "Impresionismo"?', 'Pintar de memoria', 'Captar la impresión del momento', 'Pintar abstracto', 'Usar colores puros', 2),
(5, '¿Quién pintó "El Jardín de las Delicias"?', 'Jan van Eyck', 'El Bosco', 'Pieter Bruegel', 'Albrecht Dürer', 2),
(5, '¿En qué ciudad trabajó principalmente Vermeer?', 'Amsterdam', 'Delft', 'Utrecht', 'La Haya', 2),
(5, '¿Quién pintó "La Libertad Guiando al Pueblo"?', 'Jacques-Louis David', 'Eugène Delacroix', 'Théodore Géricault', 'Jean-Auguste-Dominique Ingres', 2),
(5, '¿Cuál es el nombre real de El Greco?', 'Domenikos Theotokopoulos', 'Giorgio Vasari', 'Andrea Palladio', 'Tintoretto', 1),
(5, '¿Quién fue conocido como el pintor de bailarinas?', 'Claude Monet', 'Edgar Degas', 'Pierre-Auguste Renoir', 'Camille Pissarro', 2),
(5, '¿En qué período artístico se ubica Caravaggio?', 'Renacimiento', 'Barroco', 'Manierismo', 'Neoclasicismo', 2),
(5, '¿Quién pintó "Los Girasoles"?', 'Claude Monet', 'Vincent van Gogh', 'Paul Gauguin', 'Henri Matisse', 2),
(5, '¿Cuál es la técnica del "sfumato"?', 'Pintar rápido', 'Difuminar contornos', 'Usar colores puros', 'Pintar al aire libre', 2),
(5, '¿Quién pintó "La Escuela de Atenas"?', 'Leonardo da Vinci', 'Miguel Ángel', 'Rafael', 'Donatello', 3),
(5, '¿En qué siglo se desarrolló el Impresionismo?', 'XVII', 'XVIII', 'XIX', 'XX', 3),
(5, '¿Quién pintó "Olympia"?', 'Gustave Courbet', 'Édouard Manet', 'Edgar Degas', 'Camille Pissarro', 2),
(5, '¿Quién escribió "Cien años de soledad"?', 'Jorge Luis Borges', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Octavio Paz', 3),
(5, '¿Cuál es la primera obra de la literatura occidental?', 'La Odisea', 'La Ilíada', 'La Eneida', 'Las Metamorfosis', 2),
(5, '¿Quién escribió "Don Quijote de la Mancha"?', 'Lope de Vega', 'Miguel de Cervantes', 'Francisco de Quevedo', 'Calderón de la Barca', 2),
(5, '¿En qué siglo vivió William Shakespeare?', 'XV', 'XVI', 'XVII', 'XVIII', 2),
(5, '¿Quién escribió "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Philip K. Dick', 2),
(5, '¿Cuál es el verdadero nombre de Mark Twain?', 'Samuel Clemens', 'William Porter', 'Charles Dodgson', 'Eric Blair', 1),
(5, '¿Quién escribió "Orgullo y Prejuicio"?', 'Charlotte Brontë', 'Emily Brontë', 'Jane Austen', 'George Eliot', 3),
(5, '¿En qué idioma escribió originalmente Dante "La Divina Comedia"?', 'Latín', 'Italiano', 'Francés', 'Español', 2),
(5, '¿Quién escribió "El Señor de los Anillos"?', 'C.S. Lewis', 'J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 2),
(5, '¿Cuál es la obra más famosa de García Lorca?', 'Bodas de Sangre', 'La Casa de Bernarda Alba', 'Yerma', 'Romancero Gitano', 4),
(5, '¿Quién escribió "Moby Dick"?', 'Edgar Allan Poe', 'Herman Melville', 'Nathaniel Hawthorne', 'Washington Irving', 2),
(5, '¿En qué país nació Jorge Luis Borges?', 'España', 'Argentina', 'Uruguay', 'Chile', 2),
(5, '¿Quién escribió "Crimen y Castigo"?', 'León Tolstoi', 'Fiódor Dostoievski', 'Antón Chéjov', 'Iván Turguénev', 2),
(5, '¿Cuál es el nombre real de George Orwell?', 'Eric Blair', 'David Cornwell', 'Charles Dodgson', 'Samuel Clemens', 1),
(5, '¿Quién escribió "Los Miserables"?', 'Alexandre Dumas', 'Victor Hugo', 'Honoré de Balzac', 'Gustave Flaubert', 2),
(5, '¿En qué obra aparece el personaje de Hamlet?', 'Macbeth', 'El Rey Lear', 'Hamlet', 'Otelo', 3),
(5, '¿Quién escribió "El Principito"?', 'Jules Verne', 'Antoine de Saint-Exupéry', 'Marcel Proust', 'Albert Camus', 2),
(5, '¿Cuál fue el seudónimo de Agatha Christie?', 'Mary Westmacott', 'Ellis Peters', 'Ruth Rendell', 'P.D. James', 1),
(5, '¿Quién escribió "Rayuela"?', 'Julio Cortázar', 'Mario Vargas Llosa', 'Carlos Fuentes', 'José Donoso', 1),
(5, '¿En qué siglo se desarrolló el Romanticismo literario?', 'XVII', 'XVIII', 'XIX', 'XX', 3),
(5, '¿Quién escribió "Ulises"?', 'James Joyce', 'Virginia Woolf', 'D.H. Lawrence', 'Joseph Conrad', 1),
(5, '¿Cuál es la obra principal de Homero?', 'La Ilíada y La Odisea', 'La Eneida', 'Las Metamorfosis', 'Edipo Rey', 1),
(5, '¿Quién escribió "El Nombre de la Rosa"?', 'Italo Calvino', 'Umberto Eco', 'Alberto Moravia', 'Cesare Pavese', 2),
(5, '¿En qué país se desarrolla "Anna Karenina"?', 'Francia', 'Rusia', 'Alemania', 'Austria', 2),
(5, '¿Quién escribió "Fahrenheit 451"?', 'Isaac Asimov', 'Ray Bradbury', 'Philip K. Dick', 'Arthur C. Clarke', 2),
(5, '¿Cuál es la escultura más famosa de Miguel Ángel?', 'El Pensador', 'David', 'Venus de Milo', 'La Pietà', 2),
(5, '¿Dónde se encuentra la estatua de la Libertad?', 'Boston', 'Nueva York', 'Washington D.C.', 'Filadelfia', 2),
(5, '¿Quién esculpió "El Pensador"?', 'Auguste Rodin', 'Miguel Ángel', 'Donatello', 'Bernini', 1),
(5, '¿En qué ciudad está la Torre Eiffel?', 'Londres', 'París', 'Roma', 'Madrid', 2),
(5, '¿Cuál es el edificio más alto del mundo actualmente?', 'Empire State', 'Burj Khalifa', 'Torre CN', 'Taipei 101', 2),
(5, '¿Quién diseñó la Sagrada Familia?', 'Le Corbusier', 'Antoni Gaudí', 'Frank Lloyd Wright', 'Zaha Hadid', 2),
(5, '¿En qué país está Machu Picchu?', 'Bolivia', 'Perú', 'Ecuador', 'Colombia', 2),
(5, '¿Cuál es la maravilla del mundo antiguo que aún existe?', 'Coloso de Rodas', 'Pirámides de Giza', 'Jardines Colgantes', 'Faro de Alejandría', 2),
(5, '¿Quién esculpió la Venus de Milo?', 'Praxíteles', 'Fidias', 'Se desconoce', 'Policleto', 3),
(5, '¿En qué estilo arquitectónico está construida Notre Dame?', 'Románico', 'Gótico', 'Barroco', 'Neoclásico', 2),
(5, '¿Cuál es el museo más visitado del mundo?', 'MET', 'Louvre', 'British Museum', 'Uffizi', 2),
(5, '¿Quién diseñó el Museo Guggenheim de Bilbao?', 'Norman Foster', 'Frank Gehry', 'Zaha Hadid', 'Santiago Calatrava', 2),
(5, '¿En qué ciudad está el Coliseo?', 'Atenas', 'Roma', 'Pompeya', 'Nápoles', 2),
(5, '¿Cuál es la cúpula más grande del mundo?', 'San Pedro', 'Panteón de Roma', 'Santa Sofía', 'Brunelleschi', 2),
(5, '¿Quién esculpió "El Éxtasis de Santa Teresa"?', 'Miguel Ángel', 'Bernini', 'Donatello', 'Canova', 2),
(5, '¿En qué país está Angkor Wat?', 'Tailandia', 'Camboya', 'Vietnam', 'Laos', 2),
(5, '¿Cuál es el palacio más grande del mundo?', 'Versalles', 'Louvre', 'Palacio de Invierno', 'Forbidden City', 4),
(5, '¿Quién diseñó la Casa de la Cascada?', 'Le Corbusier', 'Frank Lloyd Wright', 'Mies van der Rohe', 'Walter Gropius', 2),
(5, '¿En qué material está esculpido el Monte Rushmore?', 'Mármol', 'Granito', 'Caliza', 'Arenisca', 2),
(5, '¿Cuál es el puente más famoso de Londres?', 'London Bridge', 'Tower Bridge', 'Westminster Bridge', 'Millennium Bridge', 2),
(5, '¿Quién diseñó el edificio de la Ópera de Sydney?', 'Jørn Utzon', 'Oscar Niemeyer', 'I.M. Pei', 'Frank Gehry', 1),
(5, '¿En qué ciudad está el Cristo Redentor?', 'São Paulo', 'Río de Janeiro', 'Salvador', 'Brasilia', 2),
(5, '¿Cuál es la iglesia más grande del mundo?', 'Notre Dame', 'San Pedro del Vaticano', 'Santa Sofía', 'San Pablo de Londres', 2),
(5, '¿Quién esculpió "La Piedad"?', 'Donatello', 'Miguel Ángel', 'Bernini', 'Ghiberti', 2),
(5, '¿En qué estilo está construido el Taj Mahal?', 'Hindú', 'Islámico mogol', 'Budista', 'Persa', 2),
(5, '¿Quién compuso "Las Cuatro Estaciones"?', 'Bach', 'Vivaldi', 'Mozart', 'Beethoven', 2),
(5, '¿Cuál es la ópera más famosa de Mozart?', 'Don Giovanni', 'Las Bodas de Fígaro', 'La Flauta Mágica', 'Todas son muy famosas', 4),
(5, '¿Quién compuso la "Novena Sinfonía"?', 'Mozart', 'Beethoven', 'Bach', 'Brahms', 2),
(5, '¿En qué período vivió Bach?', 'Renacimiento', 'Barroco', 'Clásico', 'Romántico', 2),
(5, '¿Cuál es el instrumento principal de Chopin?', 'Violín', 'Piano', 'Violonchelo', 'Órgano', 2),
(5, '¿Quién compuso "El Lago de los Cisnes"?', 'Stravinsky', 'Tchaikovsky', 'Prokofiev', 'Rachmaninoff', 2),
(5, '¿Cuántos movimientos tiene generalmente una sinfonía?', '2', '3', '4', '5', 3),
(5, '¿Quién compuso "La Consagración de la Primavera"?', 'Debussy', 'Stravinsky', 'Ravel', 'Bartók', 2),
(5, '¿Cuál es la voz masculina más grave?', 'Tenor', 'Barítono', 'Bajo', 'Contratenor', 3),
(5, '¿Quién fue conocido como "El Rey del Vals"?', 'Johann Strauss Jr.', 'Franz Liszt', 'Johannes Brahms', 'Robert Schumann', 1),
(5, '¿En qué ciudad nació Mozart?', 'Viena', 'Salzburgo', 'Múnich', 'Innsbruck', 2),
(5, '¿Cuál es el nombre completo de Bach?', 'Johann Sebastian Bach', 'Johann Christian Bach', 'Carl Philipp Emanuel Bach', 'Wilhelm Friedemann Bach', 1),
(5, '¿Quién compuso "Bolero"?', 'Debussy', 'Ravel', 'Fauré', 'Saint-Saëns', 2),
(5, '¿Cuál es la ópera más larga de Wagner?', 'Tristán e Isolda', 'El Anillo del Nibelungo', 'Parsifal', 'Los Maestros Cantores', 2),
(5, '¿Qué compositor perdió la audición?', 'Mozart', 'Beethoven', 'Schubert', 'Brahms', 2),
(5, '¿Cuál es el tempo más lento en música?', 'Andante', 'Adagio', 'Largo', 'Grave', 4),
(5, '¿Quién compuso "La Traviata"?', 'Puccini', 'Verdi', 'Rossini', 'Donizetti', 2),
(5, '¿Cuántas cuerdas tiene un violín?', '4', '5', '6', '8', 1),
(5, '¿Qué significa "fortissimo" en música?', 'Muy suave', 'Muy fuerte', 'Muy rápido', 'Muy lento', 2),
(5, '¿Quién compuso "El Carnaval de los Animales"?', 'Debussy', 'Ravel', 'Saint-Saëns', 'Fauré', 3);

INSERT INTO preguntas (categoria_id, pregunta, respuesta_1, respuesta_2, respuesta_3, respuesta_4, respuesta_correcta) VALUES
(6, '¿Cuál es la capital de Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 3),
(6, '¿Cuál es el país más pequeño del mundo?', 'San Marino', 'Mónaco', 'Vaticano', 'Nauru', 3),
(6, '¿Cuál es la capital de Canadá?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 3),
(6, '¿En qué continente está Mongolia?', 'Europa', 'Asia', 'África', 'América', 2),
(6, '¿Cuál es la capital de Brasil?', 'Río de Janeiro', 'São Paulo', 'Brasilia', 'Salvador', 3),
(6, '¿Qué país tiene más husos horarios?', 'Rusia', 'Estados Unidos', 'China', 'Francia', 4),
(6, '¿Cuál es la capital de Nueva Zelanda?', 'Auckland', 'Wellington', 'Christchurch', 'Hamilton', 2),
(6, '¿En qué país está la ciudad de Timbuctú?', 'Argelia', 'Malí', 'Níger', 'Burkina Faso', 2),
(6, '¿Cuál es la capital de Sudáfrica?', 'Ciudad del Cabo', 'Johannesburgo', 'Pretoria', 'Durban', 3),
(6, '¿Qué país es una isla y un continente?', 'Groenlandia', 'Australia', 'Madagascar', 'Nueva Guinea', 2),
(6, '¿Cuál es la capital de Suiza?', 'Zurich', 'Ginebra', 'Berna', 'Basilea', 3),
(6, '¿En qué país está la Patagonia principalmente?', 'Chile', 'Argentina', 'Ambos países', 'Uruguay', 3),
(6, '¿Cuál es la capital de Turquía?', 'Estambul', 'Ankara', 'Izmir', 'Bursa', 2),
(6, '¿Qué país tiene la forma de una bota?', 'España', 'Italia', 'Grecia', 'Portugal', 2),
(6, '¿Cuál es la capital de Egipto?', 'Alejandría', 'El Cairo', 'Luxor', 'Asuán', 2),
(6, '¿En qué país están las Cataratas del Niágara?', 'Estados Unidos', 'Canadá', 'Ambos países', 'México', 3),
(6, '¿Cuál es el país más largo del mundo?', 'Rusia', 'Chile', 'Argentina', 'Brasil', 2),
(6, '¿Cuál es la capital de Japón?', 'Osaka', 'Kyoto', 'Tokio', 'Hiroshima', 3),
(6, '¿En qué país está Machu Picchu?', 'Bolivia', 'Perú', 'Ecuador', 'Colombia', 2),
(6, '¿Cuál es la capital de Noruega?', 'Bergen', 'Oslo', 'Trondheim', 'Stavanger', 2),
(6, '¿Qué país tiene más islas en el mundo?', 'Grecia', 'Finlandia', 'Suecia', 'Noruega', 2),
(6, '¿Cuál es la capital de Argentina?', 'Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza', 3),
(6, '¿En qué país está el desierto del Sahara principalmente?', 'Egipto', 'Libia', 'Argelia', 'Múltiples países', 4),
(6, '¿Cuál es la capital de India?', 'Mumbai', 'Nueva Delhi', 'Calcuta', 'Chennai', 2),
(6, '¿Qué países comparten la Península Ibérica?', 'España y Francia', 'España y Portugal', 'Portugal y Francia', 'España, Portugal y Andorra', 4),
(6, '¿Cuál es la capital de Tailandia?', 'Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 1),
(6, '¿En qué país están los fiordos más famosos?', 'Suecia', 'Noruega', 'Dinamarca', 'Islandia', 2),
(6, '¿Cuál es la capital de Perú?', 'Arequipa', 'Trujillo', 'Lima', 'Cusco', 3),
(6, '¿Qué país es conocido como "La Tierra del Sol Naciente"?', 'China', 'Japón', 'Corea del Sur', 'Tailandia', 2),
(6, '¿Cuál es la capital de Chile?', 'Valparaíso', 'Santiago', 'Concepción', 'Antofagasta', 2),
(6, '¿Cuál es el río más largo del mundo?', 'Amazonas', 'Nilo', 'Mississippi', 'Yangtsé', 2),
(6, '¿Cuál es la montaña más alta del mundo?', 'K2', 'Everest', 'Kangchenjunga', 'Lhotse', 2),
(6, '¿Cuál es la montaña más alta de América?', 'Denali', 'Aconcagua', 'Huascarán', 'Chimborazo', 2),
(6, '¿Cuál es el lago más grande del mundo por superficie?', 'Mar Caspio', 'Lago Superior', 'Lago Victoria', 'Lago Huron', 1),
(6, '¿En qué cordillera está el Monte Everest?', 'Andes', 'Himalaya', 'Alpes', 'Rocosas', 2),
(6, '¿Cuál es el desierto más grande del mundo?', 'Sahara', 'Gobi', 'Kalahari', 'Antártico', 4),
(6, '¿Cuál es la catarata más alta del mundo?', 'Niágara', 'Iguazú', 'Salto Ángel', 'Victoria', 3),
(6, '¿En qué océano están las Islas Maldivas?', 'Atlántico', 'Pacífico', 'Índico', 'Ártico', 3),
(6, '¿Cuál es el punto más bajo de la Tierra?', 'Valle de la Muerte', 'Mar Muerto', 'Depresión de Qattara', 'Fosa de las Marianas', 2),
(6, '¿Cuál es el río más largo de Europa?', 'Danubio', 'Volga', 'Rin', 'Elba', 2),
(6, '¿En qué país están las Cataratas Victoria?', 'Sudáfrica', 'Zambia y Zimbabue', 'Botswana', 'Namibia', 2),
(6, '¿Cuál es la isla más grande del mundo?', 'Australia', 'Groenlandia', 'Nueva Guinea', 'Borneo', 2),
(6, '¿Cuál es el estrecho que separa Europa de África?', 'Bósforo', 'Gibraltar', 'Dardanelos', 'Ormuz', 2),
(6, '¿En qué océano está la Gran Barrera de Coral?', 'Atlántico', 'Pacífico', 'Índico', 'Ártico', 2),
(6, '¿Cuál es la península más grande del mundo?', 'Ibérica', 'Arábiga', 'Escandinava', 'Anatolia', 2),
(6, '¿Cuál es el volcán activo más alto del mundo?', 'Vesubio', 'Ojos del Salado', 'Cotopaxi', 'Kilimanjaro', 2),
(6, '¿En qué mar está la isla de Chipre?', 'Egeo', 'Mediterráneo', 'Negro', 'Adriático', 2),
(6, '¿Cuál es el cabo más austral de África?', 'Cabo de Buena Esperanza', 'Cabo Agulhas', 'Cabo Verde', 'Cabo Horn', 2),
(6, '¿Cuál es la cadena montañosa más larga del mundo?', 'Himalaya', 'Andes', 'Rocosas', 'Alpes', 2),
(6, '¿En qué continente está el Río Congo?', 'Asia', 'América', 'África', 'Europa', 3),
(6, '¿Cuál es el golfo más grande del mundo?', 'Golfo Pérsico', 'Golfo de México', 'Golfo de Bengala', 'Golfo de Alaska', 2),
(6, '¿Cuál es la fosa oceánica más profunda?', 'Fosa de Puerto Rico', 'Fosa de las Marianas', 'Fosa de Japón', 'Fosa de Perú-Chile', 2),
(6, '¿En qué país está el Lago Titicaca?', 'Chile', 'Bolivia y Perú', 'Ecuador', 'Argentina', 2),
(6, '¿Cuál es el río que pasa por París?', 'Loira', 'Sena', 'Ródano', 'Garona', 2),
(6, '¿Cuál es la meseta más alta del mundo?', 'Meseta Brasileña', 'Tíbet', 'Altiplano', 'Meseta de Anatolia', 2),
(6, '¿Cuál es el continente más grande?', 'África', 'Asia', 'América', 'Europa', 2),
(6, '¿Cuál es el continente más poblado?', 'África', 'Asia', 'Europa', 'América', 2),
(6, '¿Qué línea imaginaria divide la Tierra en hemisferios norte y sur?', 'Trópico de Cáncer', 'Ecuador', 'Trópico de Capricornio', 'Meridiano de Greenwich', 2),
(6, '¿Cuántos continentes hay tradicionalmente?', '5', '6', '7', '8', 3),
(6, '¿Cuál es el continente más pequeño?', 'Europa', 'Australia', 'Antártida', 'América del Norte', 2),
(6, '¿Qué océano separa América de Europa?', 'Pacífico', 'Atlántico', 'Índico', 'Ártico', 2),
(6, '¿En qué hemisferio está Argentina?', 'Norte', 'Sur', 'Ambos', 'Este', 2),
(6, '¿Cuál es la región más árida del mundo?', 'Sahara', 'Atacama', 'Gobi', 'Kalahari', 2),
(6, '¿Qué continente no tiene desiertos?', 'Asia', 'Europa', 'África', 'América', 2),
(6, '¿Cuál es el punto más al norte del mundo?', 'Alaska', 'Polo Norte', 'Groenlandia', 'Siberia', 2),
(6, '¿En qué continente está el 70% del agua dulce del mundo?', 'Asia', 'América', 'Antártida', 'Europa', 3),
(6, '¿Cuál es la selva más grande del mundo?', 'Amazonia', 'Congo', 'Borneo', 'Taiga', 1),
(6, '¿Qué mar separa Europa de África?', 'Negro', 'Mediterráneo', 'Caspio', 'Rojo', 2),
(6, '¿En qué continente está el desierto de Gobi?', 'África', 'Asia', 'Australia', 'América', 2),
(6, '¿Cuál es la tundra más grande del mundo?', 'Alaska', 'Siberia', 'Canadá', 'Escandinavia', 2),
(6, '¿Qué estrecho separa Asia de América?', 'Bering', 'Magallanes', 'Gibraltar', 'Ormuz', 1),
(6, '¿En qué océano están las Islas Galápagos?', 'Atlántico', 'Pacífico', 'Índico', 'Ártico', 2),
(6, '¿Cuál es la región más fría habitada permanentemente?', 'Alaska', 'Siberia', 'Groenlandia', 'Antártida', 2),
(6, '¿Qué canal conecta el Atlántico y el Pacífico?', 'Suez', 'Panamá', 'Corinto', 'Kiel', 2),
(6, '¿En qué hemisferio están la mayoría de los continentes?', 'Norte', 'Sur', 'Este', 'Oeste', 1),
(6, '¿Cuál es el país más poblado del mundo?', 'India', 'China', 'Estados Unidos', 'Indonesia', 2),
(6, '¿Qué país tiene más fronteras terrestres?', 'Rusia', 'Brasil', 'China', 'India', 3),
(6, '¿Cuál es el país sin salida al mar más grande?', 'Mongolia', 'Kazajistán', 'Afganistán', 'Chad', 2),
(6, '¿Qué país tiene la mayor reserva de agua dulce?', 'Rusia', 'Brasil', 'Canadá', 'Estados Unidos', 2),
(6, '¿Cuál es el país más densamente poblado?', 'Singapur', 'Mónaco', 'Bangladesh', 'Malta', 2),
(6, '¿Qué país tiene más volcanes activos?', 'Japón', 'Indonesia', 'Chile', 'Filipinas', 2),
(6, '¿Cuál es el país más joven del mundo?', 'Sudán del Sur', 'Montenegro', 'Kosovo', 'Timor Oriental', 1),
(6, '¿Qué país tiene la costa más larga?', 'Australia', 'Canadá', 'Noruega', 'Chile', 2),
(6, '¿Cuál es el país más rico del mundo per cápita?', 'Suiza', 'Luxemburgo', 'Qatar', 'Noruega', 3),
(6, '¿Qué país tiene más sitios del Patrimonio Mundial?', 'Francia', 'Italia', 'España', 'Alemania', 2),
(6, '¿Cuál es el país con más idiomas oficiales?', 'India', 'Sudáfrica', 'Suiza', 'Bélgica', 2),
(6, '¿Qué país nunca fue colonizado?', 'Tailandia', 'Etiopía', 'Japón', 'Todas las anteriores', 4),
(6, '¿Cuál es el país más montañoso del mundo?', 'Nepal', 'Suiza', 'Bután', 'Andorra', 3),
(6, '¿Qué país tiene la mayor biodiversidad?', 'Brasil', 'Colombia', 'Indonesia', 'Madagascar', 2),
(6, '¿Cuál es el país con más islas?', 'Grecia', 'Finlandia', 'Suecia', 'Noruega', 3),
(6, '¿Qué país consume más café per cápita?', 'Brasil', 'Italia', 'Finlandia', 'Colombia', 3),
(6, '¿Cuál es el país más feliz del mundo (según estudios)?', 'Suiza', 'Finlandia', 'Dinamarca', 'Noruega', 2),
(6, '¿Qué país tiene el metro más extenso?', 'Reino Unido', 'China', 'Rusia', 'Estados Unidos', 2),
(6, '¿Cuál es el país con más husos horarios en su territorio?', 'Estados Unidos', 'Rusia', 'Francia', 'Reino Unido', 3),
(6, '¿Qué país tiene la mayor reserva de petróleo?', 'Arabia Saudí', 'Venezuela', 'Irak', 'Irán', 2),
(6, '¿Cuál es el país más visitado por turistas?', 'España', 'Francia', 'Estados Unidos', 'Italia', 2),
(6, '¿Qué país tiene la esperanza de vida más alta?', 'Japón', 'Suiza', 'Singapur', 'Hong Kong', 4),
(6, '¿Cuál es el país con más premios Nobel?', 'Reino Unido', 'Estados Unidos', 'Alemania', 'Francia', 2),
(6, '¿Qué país tiene la mayor superficie de bosques?', 'Brasil', 'Rusia', 'Canadá', 'Estados Unidos', 2),
(6, '¿Cuál es el país que produce más energía renovable?', 'China', 'Estados Unidos', 'Brasil', 'Alemania', 1);

CREATE TABLE partidas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT NOT NULL,
    categoria_id INT NOT NULL,
    puntaje INT DEFAULT 0,
    cantidad_preguntas INT DEFAULT 4,
    fecha_inicio DATETIME DEFAULT CURRENT_TIMESTAMP,
    fecha_fin DATETIME NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE CASCADE,
    INDEX idx_usuario (usuario_id),
    INDEX idx_categoria (categoria_id)
);

CREATE TABLE InformePreguntas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pregunta_id INT NULL,
    editor_id INT NULL,
    tipo_accion ENUM('Edición', 'Eliminación') NOT NULL,
    motivo TEXT NOT NULL,
    fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pregunta TEXT,
    r1 TEXT,
    r2 TEXT,
    r3 TEXT,
    r4 TEXT,
    correcta INT,
    categoria_id INT,

    FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE SET NULL,
    FOREIGN KEY (editor_id) REFERENCES usuarios(id) ON DELETE SET NULL,

    INDEX (tipo_accion),
    INDEX (fecha)
);

CREATE TABLE reportes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pregunta_id INT NOT NULL,
    usuario_id INT NOT NULL,
    motivo TEXT NOT NULL,
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pregunta_id) REFERENCES preguntas(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Registro de preguntas respondidas por cada usuario para evitar repetición
CREATE TABLE IF NOT EXISTS preguntas_usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL,
    pregunta_id INT NOT NULL,
    correcta TINYINT(1) NOT NULL, -- 1 si respondió correctamente, 0 caso contrario
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_usuario_pregunta (usuario_id, pregunta_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) ON DELETE CASCADE,
    INDEX idx_usuario (usuario_id),
    INDEX idx_pregunta (pregunta_id),
    INDEX idx_usuario_correcta (usuario_id, correcta)
);