stages:
  - deploy

deploy:
  stage: deploy
  image: curlimages/curl:latest  # contenedor ligero con curl y lftp
  script:
    - echo "Subiendo proyecto a InfinityFree desde la rama $CI_COMMIT_BRANCH..."
    - apt-get update && apt-get install -y lftp
    - lftp -u $DEPLOY_USER,$DEPLOY_PASS $DEPLOY_HOST <<EOF
        mirror -R --delete --verbose ./ $DEPLOY_PATH
        bye
      EOF
  only:
    - branches